# Generated by Django 3.2.9 on 2021-11-10 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='layerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(blank=True, max_length=500, verbose_name='Group Name')),
                ('property', models.IntegerField(blank=True, default=1, verbose_name='Priority')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layerName', models.CharField(blank=True, max_length=500, verbose_name='Layer Name')),
                ('aliasName', models.CharField(blank=True, max_length=500, verbose_name='Alias Name')),
                ('groupName', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app.layergroup', verbose_name='Group Name')),
            ],
        ),
    ]
