# Generated by Django 3.2.9 on 2021-11-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layergroup',
            old_name='property',
            new_name='priority',
        ),
    ]
