# Generated by Django 3.2.9 on 2021-11-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_property_layergroup_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Layer',
        ),
        migrations.DeleteModel(
            name='layerGroup',
        ),
    ]
