# Generated by Django 3.2.9 on 2022-02-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_igwdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igwdp',
            name='completedprojects',
            field=models.IntegerField(blank=True, verbose_name='Completed Projects'),
        ),
        migrations.AlterField(
            model_name='igwdp',
            name='disbursedamount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Amount Disbursed (In Lakhs)'),
        ),
        migrations.AlterField(
            model_name='igwdp',
            name='districtscovered',
            field=models.IntegerField(blank=True, verbose_name='Districts Covered'),
        ),
        migrations.AlterField(
            model_name='igwdp',
            name='geographicalarea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Geographical Area (Ha)'),
        ),
        migrations.AlterField(
            model_name='igwdp',
            name='householdscovered',
            field=models.IntegerField(blank=True, verbose_name='Households Covered'),
        ),
        migrations.AlterField(
            model_name='igwdp',
            name='ongoingprojects',
            field=models.IntegerField(blank=True, max_length=500, verbose_name='OnGoing Projects'),
        ),
        migrations.AlterField(
            model_name='igwdp',
            name='pfacount',
            field=models.IntegerField(blank=True, verbose_name='Total PFAs'),
        ),
        migrations.AlterField(
            model_name='igwdp',
            name='sanctionedamount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Amount Sanctioned (In Lakhs)'),
        ),
        migrations.AlterField(
            model_name='igwdp',
            name='treatablearea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Treatable Area (Ha)'),
        ),
        migrations.AlterField(
            model_name='igwdp',
            name='utilizedamount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Amount Utilized (In Lakhs)'),
        ),
        migrations.AlterField(
            model_name='igwdp',
            name='watershedscount',
            field=models.IntegerField(blank=True, verbose_name='No of Watersheds'),
        ),
    ]
