# Generated by Django 3.2.9 on 2023-05-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_igwdp_ongoingprojects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igwdp',
            options={'managed': True, 'verbose_name': 'IGWDP', 'verbose_name_plural': 'IGWDP'},
        ),
    ]
